apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - loki.yaml
  - prometheus.yaml
  - grafana.yaml
  - alertmanager.yaml
  - gateway-dashboard.yaml
  - services-dashboard.yaml
