spring:
  application:
    name: blog
  profiles:
    active: dev

# 日志
logging:
  level:
    root: INFO
    cn.kuma.blog: DEBUG
    com.kuma.boot: INFO

# Swagger / SpringDoc
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true



