server:
  port: 8088

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.jdbc.autoconfigure.health.DataSourceHealthContributorAutoConfiguration
      - org.springframework.boot.kafka.autoconfigure.KafkaAutoConfiguration

# 启用分布式事务 RM（Resource Manager）
kuma:
  tx:
    enabled: true
