apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-fronted
  namespace: blog
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: blog-fronted
  template:
    metadata:
      labels:
        app: blog-fronted
    spec:
      containers:
        - name: nginx
          image: nginx:1.26.2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: dist
              mountPath: /usr/share/nginx/html
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
      volumes:
        - name: dist
          hostPath:
            path: /data/blog/fronted/dist
            type: DirectoryOrCreate
        - name: nginx-conf
          hostPath:
            path: /data/blog/fronted/nginx/default.conf
            type: File
---
apiVersion: v1
kind: Service
metadata:
  name: blog-fronted
  namespace: blog
spec:
  selector:
    app: blog-fronted
  ports:
    - port: 80
      targetPort: 80
