apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-qdrant
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-qdrant
  template:
    metadata:
      labels:
        app: blog-qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:v1.16.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6333
            - containerPort: 6334
          volumeMounts:
            - name: qdrant-data
              mountPath: /qdrant/storage
      volumes:
        - name: qdrant-data
          hostPath:
            path: /data/qdrant
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: blog-qdrant
  namespace: blog
spec:
  selector:
    app: blog-qdrant
  ports:
    - name: http
      port: 6333
      targetPort: 6333
    - name: grpc
      port: 6334
      targetPort: 6334
