name: Apply UAA K8s Configs

on:
  push:
    branches: [master]
    paths:
      - 'kuma-project/kuma-project-uaa/k8s/**'

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare k8s dir on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.BLOG_SERVER_HOST }}
          username: ${{ secrets.BLOG_SERVER_USER }}
          key: ${{ secrets.BLOG_SERVER_SSH_KEY }}
          script: mkdir -p /data/k8s/base

      - name: Copy k8s files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.BLOG_SERVER_HOST }}
          username: ${{ secrets.BLOG_SERVER_USER }}
          key: ${{ secrets.BLOG_SERVER_SSH_KEY }}
          source: kuma-project/kuma-project-uaa/k8s/*
          target: /data/k8s/base/
          strip_components: 3

      - name: Apply k8s configs
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.BLOG_SERVER_HOST }}
          username: ${{ secrets.BLOG_SERVER_USER }}
          key: ${{ secrets.BLOG_SERVER_SSH_KEY }}
          script: kubectl apply -f /data/k8s/base/
